# Generated by Django 4.2.2 on 2023-06-21 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_create'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='create',
            new_name='create_time',
        ),
    ]
